### ISSUE TITLE
Better testing incl integration tests for strats and settings

### ISSUE THREAD

**Issue by Siddharth2207** [rainlanguage/rain.dex.pubstrats#63]
### Motivation
- Currently there is a lot of boilerplate involved in dotrain while writing strategies specifically in the yml section where keys `networks` , `orderbooks`, `deployers`, `subgraphs`  are repeatedly present in different dotrains. 
- Goal is to reduce the boilerplate by having a single `settings.yml` file within the repo and these setting will be pulled into the dotrain file during composition via orderbook cli just like in the raindex app.  Further the orderbook cli should be able to generate complete `addOrder` calldata from the composed dotrain for any specified deployment key. 

So for testing strats/settings
- one settings.yml in the repo
- for every strat we merge that config in first (just like in the app) and then do our fork tests
- we test every strat for every network in the settings
- we use one dotrain per strat but have a deployment in the yaml for every network

For testing app/strat
- we now use the rust crates to get the addorder calldata (via the cli), so we at least know some strat is compatible with the underlying rust

For testing app/settings
- we can use the rust crates to ping the subgraph endpoints - now we know the app is compatible with that subgraph endpoint
- we can use the rust crates to get all the authoringmeta for the deployers in settings. now we know the app can get the words

### Implementation 
- [x] Update OrderBook cli composition where `.rain` and `setting.yml` are passed as a different inputs to the cli command and the cli gives the composed dotrain (including the post-add-order tasks). (@hardyjosh already added it)
- [x] Add CLI command to generate addOrder callData for a specified deployment for a particular composition. https://github.com/rainlanguage/rain.orderbook/pull/782
- [x] Add CLI command to get settings associated with a particular composition.  https://github.com/rainlanguage/rain.orderbook/pull/782
- [x] Update [std-test](https://github.com/h20liquidity/h20.test-std) with the updated cli. https://github.com/h20liquidity/h20.test-std/pull/16
- [x] Write tests to ensure integrity of composition and the generated calldata for different deployments rainlanguage/rain.dex.pubstrats#65 
- [ ] Update strats to include a deployment for every network included in settings, as a way to test every strat for every network (just add one other network for now, base is fine) rainlanguage/rain.dex.pubstrats#66 
- [x] rainlanguage/rain.orderbook#797
- [ ] Allow for composition in the yaml - allow for referencing other values in the yaml by path (syntax tbc @thedavidmeister)
- [x] rainlanguage/rain.orderbook#791
- [x] rainlanguage/rain.orderbook#789
- [x] rainlanguage/rain.dex.pubstrats#77
- [x] rainlanguage/rain.orderbook#790
- [x] rainlanguage/rain.orderbook#802
- [x] #79
- [x] https://github.com/h20liquidity/h20.test-std/pull/17
- [x] https://github.com/rainlanguage/rain.dex.pubstrats/pull/80
- [x] https://github.com/h20liquidity/h20.test-std/pull/18
- [x] #82 
- [ ] Add settings for all networks, update strats to include deployments for all networks
- [x] rainlanguage/rain.orderbook#792
- [ ] Create a basic GUI that will take a customer strat and create a one-off dist with pre-built calldata that can be pushed to hosting with a unique URL.

**Comment by dcatki** [comment]
@Siddharth2207 are you still working on this? What's the status?

**Comment by dcatki** [comment]
@Siddharth2207

**Comment by Siddharth2207** [comment]
@hardyjosh For this issue I see that the flake is been updated with the action that we merged along with ob cli commands, but the CI is removed and it may require h20.test-std deps to be updated which I haven't checked yet. So should I document this here and close the issue(it's just sitting on kanban) or update the deps and re-add the CI atleast like for subgraph check actions

**Comment by thedavidmeister** [comment]
repo is being archived so this is closing out
